### ISSUE TITLE
configure datetime picker

### ISSUE THREAD

**Issue by ecesari** [zeyneplervesarp/swe574-javagang#13]
currently datetimepicker component displays all the dates, it should only display future dates when creating new services

**Comment by ZeynepDYilmaz** [comment]
will add date to notifications

**Comment by ZeynepDYilmaz** [comment]
try this: `            <v-date-picker
                      v-model="dateTermino"
                      :min="new Date().toISOString().substr(0, 10)"
              ></v-date-picker>`

**Comment by ZeynepDYilmaz** [comment]
closed becasue low priority
