### ISSUE TITLE
axios delete doesn't work

### ISSUE THREAD

**Issue by ecesari** [zeyneplervesarp/swe574-javagang#147]
delete method on http.js doesn't work and returns a network error, this seems like a bug on axios request construction.
the method of unfeature has been changed from being a delete endpoint to post endpoint

**Comment by ZeynepDYilmaz** [comment]
same with the delete service and delete user enpoints.

**Comment by ecesari** [comment]
> same with the delete service and delete user enpoints.

@ZeynepDYilmaz if this is the bug mentioned in #133 that is another bug regarding the backend. This bug is about the endpoint not sending a request to the backend with the delete method.

**Comment by ZeynepDYilmaz** [comment]
@ecesari the bug mentioned in #133 is a different bug related to the db delete request.

**Comment by ecesari** [comment]
> @ecesari the bug mentioned in #133 is a different bug related to the db delete request.

oh ok my bad

**Comment by zynpgltkn** [comment]
Resolved with this [code](https://github.com/zeyneplervesarp/swe574-javagang/blob/develop/backend/src/main/java/com/swe573/socialhub/config/SecurityConfiguration.java)

added allowed DELETE method to CORS config
