### ISSUE TITLE
Final Project Group Report

### ISSUE THREAD

**Issue by ZeynepDYilmaz** [zeyneplervesarp/swe574-javagang#256]
Please find specs here:
https://swe573-574-2021-22.slack.com/files/U02HHUKJ9EF/F03FTPGAWAW/swe574_2022_spring_final_deliverables.pdf

**Comment by ZeynepDYilmaz** [comment]
I'll be adding to the report here: https://docs.google.com/document/d/19nkURlfna_eD4d6kBA6g-tAiprYaqvSw92c2kN0V9_0/edit#

**Comment by ZDenizYStenhaug** [comment]
The final report can be found here: https://github.com/zeyneplervesarp/swe574-javagang/blob/master/SWE%20574%202022%20Spring-FinalProjectReport-Group1.pdf
