### ISSUE TITLE
Highlevel Review of Requirements

### ISSUE THREAD

**Issue by ZeynepDYilmaz** [zeyneplervesarp/swe574-javagang#65]
1. give id to requirement titles.
every title must have an id, and the requirements under it must have related numbering.
Ex:
1. Homepage
  1.1 req. 1
  1.2 req. 2
  ...

2. UI specifications are not requirements. (ex: There shall be a login page. ex: requirements about form fields. 164. 172.)
Req. about the profile ahould be about what the user can do in the profile page.
173? "the system shall provide personalized search results based on user's history and social network"

**Comment by zynpgltkn** [comment]
Requirements are given ids. Some requirements are converted from "UI Specifications" to "something a user can do" .
